version: "3.9"

services:
  app:
    build: .
    container_name: java_app
    ports:
      - "8087:8505"
    env_file:
      - /home/ubuntu/.env
    depends_on:
      - postgres_db
      - redis
    networks:
      - backend

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    external: true
